#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

brew tap homebrew/services
brew tap caskroom/cask
brew tap caskroom/versions
brew tap caskroom/cask-fonts

# ==============================================================================
# Install Cask apps/resources
# ==============================================================================

brew cask install firefox
brew cask install google-chrome
brew cask install mpv
brew cask install sublime-text
brew cask install transmission
brew cask install docker
brew cask install alfred
brew cask install iterm2
brew cask install sketch
brew cask install phpstorm
brew cask install slack 
brew cask install sublime-merge
brew cask install font-fira-code

# ==============================================================================
# Install standard packages
# ==============================================================================
brew install php
brew install bash
brew install git
brew install wget
brew install youtube-dl
brew install curl
brew install tmux
brew install tree
brew install composer
brew install bash-completion@2

# Remove outdated versions from the cellar
brew cleanup
