#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

brew tap homebrew/services
brew tap caskroom/cask
brew tap caskroom/versions

# ==============================================================================
# Install Cask apps/resources
# ==============================================================================

brew cask install firefox
brew cask install google-chrome
brew cask install mpv
brew cask install sublime-text3
brew cask install transmission
brew cask install virtualbox
brew cask install docker
brew cask install alfred
brew cask install iterm2
brew cask install sketch

# ==============================================================================
# Install standard packages
# ==============================================================================

brew install git
brew install wget
brew install youtube-dl
brew install docker-completion
brew install docker-compose-completion
brew install curl
brew install tmux
brew install tree
brew install bash-completion

# Remove outdated versions from the cellar
brew cleanup